class CharacterName:
    MARIO = "Mario"
    DK = "Donkey Kong"
    LINK = "Link"
    SAMUS = "Samus"
    YOSHI = "Yoshi"
    KIRBY = "Kirby"
    FOX = "Fox"
    PIKACHU = "Pikachu"
    NESS = "Ness"
    CF = "Captain Falcon"
    BOWSER = "Bowser"
    PEACH = "Peach"
    IC = "Ice Climbers"
    ZELDA = "Zelda"
    SHEIK = "Sheik"
    LUIGI = "Luigi"
    JIGGLYPUFF = "Jigglypuff"
    MEWTWO = "Mewtwo"
    MARTH = "Marth"
    GW = "Mr. Game & Watch"
    DRMARIO = "Dr. Mario"
    GANONDORF = "Ganondorf"
    FALCO = "Falco"
    YLINK = "Young Link"
    PICHU = "Pichu"
    ROY = "Roy"

def getCharacterList():
    return [{"id": name, "name": getattr(CharacterName,name)} for name in dir(CharacterName) if not name.startswith('__') ]